# -*- coding: utf-8 -*-
# data_localization.py — بيانات الترجمة والمناطق الجغرافية
# مُستخرَج من bot_legacy.py

# ======== كودات اللغة للطقس ========
LANG_CODES = {
    "العربية 🇮🇶": "ar",
    "English 🇬🇧": "en",
    "Русский 🇷🇺": "ru",
    "فارسی 🇮🇷": "fa",
    "हिन्दी 🇮🇳": "hi",
    "Português 🇧🇷": "pt",
    "Türkçe 🇹🇷": "tr",
    "اردو 🇵🇰": "ur",
    "Deutsch 🇩🇪": "de",
    "Українська 🇺🇦": "uk",
    "Italiano 🇮🇹": "it",
    "Español 🇲🇽": "es",
    "Français 🇫🇷": "fr",
}

# ======== الدول والمحافظات ========
countries = {
    # ═══ العربية: جميع الدول العربية ═══
    "العربية 🇮🇶": {
        "العراق 🇮🇶": [
            "بغداد", "البصرة", "الموصل", "أربيل", "السليمانية",
            "ذي قار", "ديالى", "بابل", "الأنبار", "النجف",
            "كركوك", "واسط", "كربلاء", "صلاح الدين", "المثنى",
            "ميسان", "القادسية", "دهوك",
        ],
        "السعودية 🇸🇦": [],
        "الكويت 🇰🇼": [],
        "قطر 🇶🇦": [],
        "الإمارات العربية المتحدة 🇦🇪": [],
        "البحرين 🇧🇭": [],
        "عُمان 🇴🇲": [],
        "اليمن 🇾🇪": [],
        "سوريا 🇸🇾": [],
        "لبنان 🇱🇧": [],
        "الأردن 🇯🇴": [],
        "فلسطين 🇵🇸": [],
        "مصر 🇪🇬": [],
        "ليبيا 🇱🇾": [],
        "تونس 🇹🇳": [],
        "الجزائر 🇩🇿": [],
        "المغرب 🇲🇦": [],
        "موريتانيا 🇲🇷": [],
        "السودان 🇸🇩": [],
        "الصومال 🇸🇴": [],
        "جيبوتي 🇩🇯": [],
        "جزر القمر 🇰🇲": [],
    },
    # ═══ English: all major English-speaking countries ═══
    "English 🇬🇧": {
        "United States 🇺🇸": [],
        "United Kingdom 🇬🇧": [],
        "Australia 🇦🇺": [],
        "Canada 🇨🇦": [],
        "Ireland 🇮🇪": [],
        "New Zealand 🇳🇿": [],
        "South Africa 🇿🇦": [],
        "Nigeria 🇳🇬": [],
        "Ghana 🇬🇭": [],
        "Kenya 🇰🇪": [],
        "Tanzania 🇹🇿": [],
        "Uganda 🇺🇬": [],
        "Zimbabwe 🇿🇼": [],
        "Zambia 🇿🇲": [],
        "Botswana 🇧🇼": [],
        "Singapore 🇸🇬": [],
        "Philippines 🇵🇭": [],
        "Jamaica 🇯🇲": [],
        "Trinidad & Tobago 🇹🇹": [],
        "Barbados 🇧🇧": [],
        "Malta 🇲🇹": [],
        "Cyprus 🇨🇾": [],
        "Guyana 🇬🇾": [],
        "Belize 🇧🇿": [],
        "Bahamas 🇧🇸": [],
    },
    # ═══ Русский: все страны со значительным русскоязычным населением ═══
    "Русский 🇷🇺": {
        "Россия 🇷🇺": [],
        "Беларусь 🇧🇾": [],
        "Казахстан 🇰🇿": [],
        "Узбекистан 🇺🇿": [],
        "Кыргызстан 🇰🇬": [],
        "Таджикистан 🇹🇯": [],
        "Армения 🇦🇲": [],
        "Азербайджан 🇦🇿": [],
        "Грузия 🇬🇪": [],
        "Молдова 🇲🇩": [],
        "Латвия 🇱🇻": [],
        "Литва 🇱🇹": [],
        "Эстония 🇪🇪": [],
        "Израиль 🇮🇱": [],
        "Германия 🇩🇪": [],
    },
    # ═══ فارسی: کشورهایی که فارسی در آنها رسمی یا رایج است ═══
    "فارسی 🇮🇷": {
        "ایران 🇮🇷": [],
        "افغانستان 🇦🇫": [],
        "تاجیکستان 🇹🇯": [],
        "ازبکستان 🇺🇿": [],
        "پاکستان 🇵🇰": [],
        "عراق 🇮🇶": [],
        "بحرین 🇧🇭": [],
        "کویت 🇰🇼": [],
        "امارات متحده عربی 🇦🇪": [],
    },
    # ═══ हिन्दी: हिन्दी भाषी देश और प्रवासी ═══
    "हिन्दी 🇮🇳": {
        "भारत 🇮🇳": [],
        "नेपाल 🇳🇵": [],
        "फ़िजी 🇫🇯": [],
        "मॉरीशस 🇲🇺": [],
        "गुयाना 🇬🇾": [],
        "त्रिनिदाद और टोबैगो 🇹🇹": [],
        "सूरीनाम 🇸🇷": [],
        "दक्षिण अफ्रीका 🇿🇦": [],
        "संयुक्त अरब अमीरात 🇦🇪": [],
        "कनाडा 🇨🇦": [],
        "संयुक्त राज्य अमेरिका 🇺🇸": [],
        "यूनाइटेड किंगडम 🇬🇧": [],
    },
    # ═══ Português: todos os países lusófonos ═══
    "Português 🇧🇷": {
        "Brasil 🇧🇷": [],
        "Portugal 🇵🇹": [],
        "Angola 🇦🇴": [],
        "Moçambique 🇲🇿": [],
        "Cabo Verde 🇨🇻": [],
        "Guiné-Bissau 🇬🇼": [],
        "São Tomé e Príncipe 🇸🇹": [],
        "Guiné Equatorial 🇬🇶": [],
        "Timor-Leste 🇹🇱": [],
        "Macau 🇲🇴": [],
    },
    # ═══ Türkçe: Türkçe konuşulan ülkeler ═══
    "Türkçe 🇹🇷": {
        "Türkiye 🇹🇷": [],
        "Azerbaycan 🇦🇿": [],
        "Kıbrıs 🇨🇾": [],
        "Kazakistan 🇰🇿": [],
        "Özbekistan 🇺🇿": [],
        "Türkmenistan 🇹🇲": [],
        "Kırgızistan 🇰🇬": [],
        "Almanya 🇩🇪": [],
        "Avusturya 🇦🇹": [],
    },
    # ═══ اردو: اردو بولنے والے ممالک ═══
    "اردو 🇵🇰": {
        "پاکستان 🇵🇰": [],
        "بھارت 🇮🇳": [],
        "بنگلہ دیش 🇧🇩": [],
        "افغانستان 🇦🇫": [],
        "متحدہ عرب امارات 🇦🇪": [],
        "سعودی عرب 🇸🇦": [],
        "کویت 🇰🇼": [],
        "قطر 🇶🇦": [],
        "بحرین 🇧🇭": [],
        "عُمان 🇴🇲": [],
        "مملکت متحدہ 🇬🇧": [],
        "کینیڈا 🇨🇦": [],
        "امریکہ 🇺🇸": [],
    },
    # ═══ Deutsch: alle deutschsprachigen Länder ═══
    "Deutsch 🇩🇪": {
        "Deutschland 🇩🇪": [],
        "Österreich 🇦🇹": [],
        "Schweiz 🇨🇭": [],
        "Liechtenstein 🇱🇮": [],
        "Luxemburg 🇱🇺": [],
        "Belgien 🇧🇪": [],
        "Südtirol (Italien) 🇮🇹": [],
        "Namibia 🇳🇦": [],
    },
    # ═══ Українська: країни з українськомовним населенням ═══
    "Українська 🇺🇦": {
        "Україна 🇺🇦": [],
        "Канада 🇨🇦": [],
        "США 🇺🇸": [],
        "Польща 🇵🇱": [],
        "Молдова 🇲🇩": [],
        "Словаччина 🇸🇰": [],
        "Румунія 🇷🇴": [],
        "Угорщина 🇭🇺": [],
        "Австралія 🇦🇺": [],
    },
    # ═══ Italiano: tutti i paesi italofoni ═══
    "Italiano 🇮🇹": {
        "Italia 🇮🇹": [],
        "Svizzera 🇨🇭": [],
        "San Marino 🇸🇲": [],
        "Città del Vaticano 🇻🇦": [],
        "Malta 🇲🇹": [],
        "Croazia 🇭🇷": [],
        "Slovenia 🇸🇮": [],
        "Argentina 🇦🇷": [],
        "Brasile 🇧🇷": [],
        "Uruguay 🇺🇾": [],
    },
    # ═══ Español: todos los países hispanohablantes ═══
    "Español 🇲🇽": {
        "México 🇲🇽": [],
        "España 🇪🇸": [],
        "Argentina 🇦🇷": [],
        "Colombia 🇨🇴": [],
        "Chile 🇨🇱": [],
        "Perú 🇵🇪": [],
        "Venezuela 🇻🇪": [],
        "Ecuador 🇪🇨": [],
        "Bolivia 🇧🇴": [],
        "Paraguay 🇵🇾": [],
        "Uruguay 🇺🇾": [],
        "Cuba 🇨🇺": [],
        "República Dominicana 🇩🇴": [],
        "Guatemala 🇬🇹": [],
        "Honduras 🇭🇳": [],
        "El Salvador 🇸🇻": [],
        "Nicaragua 🇳🇮": [],
        "Costa Rica 🇨🇷": [],
        "Panamá 🇵🇦": [],
        "Guinea Ecuatorial 🇬🇶": [],
        "Puerto Rico 🇵🇷": [],
    },
}

# ======== خريطة أسماء المحافظات/المدن → أسماء OWM بالإنجليزي ========
# مطلوبة لأن OWM لا يدعم الأسماء العربية/المحلية دائماً بشكل موثوق
PROVINCE_TO_OWM = {
    # ── المحافظات العراقية ──
    "بغداد":       "Baghdad",
    "البصرة":      "Basra",
    "الموصل":      "Mosul",
    "أربيل":       "Erbil",
    "السليمانية":  "Sulaymaniyah",
    "ذي قار":      "Nasiriyah",
    "ديالى":       "Baqubah",
    "بابل":        "Hillah",
    "الأنبار":     "Ramadi",
    "النجف":       "Najaf",
    "كركوك":       "Kirkuk",
    "واسط":        "Kut",
    "كربلاء":      "Karbala",
    "صلاح الدين":  "Tikrit",
    "المثنى":      "Samawah",
    "ميسان":       "Amarah",
    "القادسية":    "Diwaniyah",
    "دهوك":        "Duhok",
}

# ======== عواصم الدول (لحساب الطقس عندما لا توجد محافظات) ========
COUNTRY_CAPITALS = {
    # ── عربي ──
    "العراق 🇮🇶":                   "Baghdad",
    "السعودية 🇸🇦":                  "Riyadh",
    "الكويت 🇰🇼":                   "Kuwait City",
    "قطر 🇶🇦":                      "Doha",
    "الإمارات العربية المتحدة 🇦🇪":  "Abu Dhabi",
    "البحرين 🇧🇭":                  "Manama",
    "عُمان 🇴🇲":                    "Muscat",
    "اليمن 🇾🇪":                    "Sanaa",
    "سوريا 🇸🇾":                    "Damascus",
    "لبنان 🇱🇧":                    "Beirut",
    "الأردن 🇯🇴":                   "Amman",
    "فلسطين 🇵🇸":                   "Jerusalem",
    "مصر 🇪🇬":                      "Cairo",
    "ليبيا 🇱🇾":                    "Tripoli",
    "تونس 🇹🇳":                     "Tunis",
    "الجزائر 🇩🇿":                  "Algiers",
    "المغرب 🇲🇦":                   "Rabat",
    "موريتانيا 🇲🇷":                "Nouakchott",
    "السودان 🇸🇩":                  "Khartoum",
    "الصومال 🇸🇴":                  "Mogadishu",
    "جيبوتي 🇩🇯":                   "Djibouti",
    "جزر القمر 🇰🇲":                "Moroni",
    # ── English ──
    "United States 🇺🇸":            "Washington",
    "United Kingdom 🇬🇧":           "London",
    "Australia 🇦🇺":                "Canberra",
    "Canada 🇨🇦":                   "Ottawa",
    "Ireland 🇮🇪":                  "Dublin",
    "New Zealand 🇳🇿":              "Wellington",
    "South Africa 🇿🇦":             "Pretoria",
    "Nigeria 🇳🇬":                  "Abuja",
    "Ghana 🇬🇭":                    "Accra",
    "Kenya 🇰🇪":                    "Nairobi",
    "Tanzania 🇹🇿":                 "Dodoma",
    "Uganda 🇺🇬":                   "Kampala",
    "Zimbabwe 🇿🇼":                 "Harare",
    "Zambia 🇿🇲":                   "Lusaka",
    "Botswana 🇧🇼":                 "Gaborone",
    "Singapore 🇸🇬":                "Singapore",
    "Philippines 🇵🇭":              "Manila",
    "Jamaica 🇯🇲":                  "Kingston",
    "Trinidad & Tobago 🇹🇹":        "Port of Spain",
    "Barbados 🇧🇧":                 "Bridgetown",
    "Malta 🇲🇹":                    "Valletta",
    "Cyprus 🇨🇾":                   "Nicosia",
    "Guyana 🇬🇾":                   "Georgetown",
    "Belize 🇧🇿":                   "Belmopan",
    "Bahamas 🇧🇸":                  "Nassau",
    # ── Русский ──
    "Россия 🇷🇺":                   "Moscow",
    "Беларусь 🇧🇾":                 "Minsk",
    "Казахстан 🇰🇿":                "Astana",
    "Узбекистан 🇺🇿":               "Tashkent",
    "Кыргызстан 🇰🇬":              "Bishkek",
    "Таджикистан 🇹🇯":              "Dushanbe",
    "Армения 🇦🇲":                  "Yerevan",
    "Азербайджан 🇦🇿":              "Baku",
    "Грузия 🇬🇪":                   "Tbilisi",
    "Молдова 🇲🇩":                  "Chisinau",
    "Латвия 🇱🇻":                   "Riga",
    "Литва 🇱🇹":                    "Vilnius",
    "Эстония 🇪🇪":                  "Tallinn",
    "Израиль 🇮🇱":                  "Jerusalem",
    "Германия 🇩🇪":                 "Berlin",
    # ── فارسی ──
    "ایران 🇮🇷":                    "Tehran",
    "افغانستان 🇦🇫":                "Kabul",
    "تاجیکستان 🇹🇯":               "Dushanbe",
    "ازبکستان 🇺🇿":                 "Tashkent",
    "پاکستان 🇵🇰":                  "Islamabad",
    "عراق 🇮🇶":                     "Baghdad",
    "بحرین 🇧🇭":                    "Manama",
    "کویت 🇰🇼":                     "Kuwait City",
    "امارات متحده عربی 🇦🇪":        "Abu Dhabi",
    # ── हिन्दी ──
    "भारत 🇮🇳":                     "New Delhi",
    "नेपाल 🇳🇵":                    "Kathmandu",
    "फ़िजी 🇫🇯":                    "Suva",
    "मॉरीशस 🇲🇺":                   "Port Louis",
    "गुयाना 🇬🇾":                   "Georgetown",
    "त्रिनिदाद और टोबैगो 🇹🇹":      "Port of Spain",
    "सूरीनाम 🇸🇷":                  "Paramaribo",
    "दक्षिण अफ्रीका 🇿🇦":           "Pretoria",
    "संयुक्त अरब अमीरात 🇦🇪":       "Abu Dhabi",
    "कनाडा 🇨🇦":                    "Ottawa",
    "संयुक्त राज्य अमेरिका 🇺🇸":     "Washington",
    "यूनाइटेड किंगडम 🇬🇧":          "London",
    # ── Português ──
    "Brasil 🇧🇷":                   "Brasilia",
    "Portugal 🇵🇹":                 "Lisbon",
    "Angola 🇦🇴":                   "Luanda",
    "Moçambique 🇲🇿":               "Maputo",
    "Cabo Verde 🇨🇻":               "Praia",
    "Guiné-Bissau 🇬🇼":             "Bissau",
    "São Tomé e Príncipe 🇸🇹":      "Sao Tome",
    "Guiné Equatorial 🇬🇶":         "Malabo",
    "Timor-Leste 🇹🇱":              "Dili",
    "Macau 🇲🇴":                    "Macao",
    # ── Türkçe ──
    "Türkiye 🇹🇷":                  "Ankara",
    "Azerbaycan 🇦🇿":               "Baku",
    "Kıbrıs 🇨🇾":                   "Nicosia",
    "Kazakistan 🇰🇿":               "Astana",
    "Özbekistan 🇺🇿":               "Tashkent",
    "Türkmenistan 🇹🇲":             "Ashgabat",
    "Kırgızistan 🇰🇬":              "Bishkek",
    "Almanya 🇩🇪":                  "Berlin",
    "Avusturya 🇦🇹":                "Vienna",
    # ── اردو ──
    "پاکستان 🇵🇰":                  "Islamabad",
    "بھارت 🇮🇳":                    "New Delhi",
    "بنگلہ دیش 🇧🇩":               "Dhaka",
    "افغانستان 🇦🇫":                "Kabul",
    "متحدہ عرب امارات 🇦🇪":         "Abu Dhabi",
    "سعودی عرب 🇸🇦":               "Riyadh",
    "کویت 🇰🇼":                     "Kuwait City",
    "قطر 🇶🇦":                      "Doha",
    "بحرین 🇧🇭":                    "Manama",
    "عُمان 🇴🇲":                    "Muscat",
    "مملکت متحدہ 🇬🇧":              "London",
    "کینیڈا 🇨🇦":                   "Ottawa",
    "امریکہ 🇺🇸":                   "Washington",
    # ── Deutsch ──
    "Deutschland 🇩🇪":              "Berlin",
    "Österreich 🇦🇹":               "Vienna",
    "Schweiz 🇨🇭":                  "Bern",
    "Liechtenstein 🇱🇮":            "Vaduz",
    "Luxemburg 🇱🇺":                "Luxembourg",
    "Belgien 🇧🇪":                  "Brussels",
    "Südtirol (Italien) 🇮🇹":       "Bolzano",
    "Namibia 🇳🇦":                  "Windhoek",
    # ── Українська ──
    "Україна 🇺🇦":                  "Kyiv",
    "Канада 🇨🇦":                   "Ottawa",
    "США 🇺🇸":                      "Washington",
    "Польща 🇵🇱":                   "Warsaw",
    "Молдова 🇲🇩":                  "Chisinau",
    "Словаччина 🇸🇰":               "Bratislava",
    "Румунія 🇷🇴":                  "Bucharest",
    "Угорщина 🇭🇺":                 "Budapest",
    "Австралія 🇦🇺":                "Canberra",
    # ── Italiano ──
    "Italia 🇮🇹":                   "Rome",
    "Svizzera 🇨🇭":                 "Bern",
    "San Marino 🇸🇲":               "San Marino",
    "Città del Vaticano 🇻🇦":       "Vatican City",
    "Malta 🇲🇹":                    "Valletta",
    "Croazia 🇭🇷":                  "Zagreb",
    "Slovenia 🇸🇮":                 "Ljubljana",
    "Argentina 🇦🇷":                "Buenos Aires",
    "Brasile 🇧🇷":                  "Brasilia",
    "Uruguay 🇺🇾":                  "Montevideo",
    # ── Español ──
    "México 🇲🇽":                   "Mexico City",
    "España 🇪🇸":                   "Madrid",
    "Colombia 🇨🇴":                 "Bogota",
    "Chile 🇨🇱":                    "Santiago",
    "Perú 🇵🇪":                     "Lima",
    "Venezuela 🇻🇪":                "Caracas",
    "Ecuador 🇪🇨":                  "Quito",
    "Bolivia 🇧🇴":                  "Sucre",
    "Paraguay 🇵🇾":                 "Asuncion",
    "Cuba 🇨🇺":                     "Havana",
    "República Dominicana 🇩🇴":     "Santo Domingo",
    "Guatemala 🇬🇹":                "Guatemala City",
    "Honduras 🇭🇳":                 "Tegucigalpa",
    "El Salvador 🇸🇻":              "San Salvador",
    "Nicaragua 🇳🇮":                "Managua",
    "Costa Rica 🇨🇷":               "San Jose",
    "Panamá 🇵🇦":                   "Panama City",
    "Guinea Ecuatorial 🇬🇶":        "Malabo",
    "Puerto Rico 🇵🇷":              "San Juan",
    # ── Français ──
    "France 🇫🇷":                   "Paris",
    "Belgique 🇧🇪":                 "Brussels",
    "Suisse 🇨🇭":                   "Bern",
    "Canada 🇨🇦":                   "Ottawa",
    "Maroc 🇲🇦":                    "Rabat",
    "Algérie 🇩🇿":                  "Algiers",
    "Tunisie 🇹🇳":                  "Tunis",
    "Côte d'Ivoire 🇨🇮":            "Abidjan",
    "Sénégal 🇸🇳":                  "Dakar",
    "Cameroun 🇨🇲":                 "Yaounde",
    "Mali 🇲🇱":                     "Bamako",
    "Burkina Faso 🇧🇫":             "Ouagadougou",
    "Niger 🇳🇪":                    "Niamey",
    "Tchad 🇹🇩":                    "N'Djamena",
    "Congo 🇨🇬":                    "Brazzaville",
    "Madagascar 🇲🇬":               "Antananarivo",
    "Luxembourg 🇱🇺":               "Luxembourg",
    "Haïti 🇭🇹":                    "Port-au-Prince",
}

# ======== دالة مساعدة: تحويل اسم المحافظة/الدولة إلى اسم OWM ========
def _to_owm_city(province: str, country: str = "") -> str:
    """يحوّل اسم المحافظة/الدولة المخزّن إلى اسم مدينة تقبله OWM API."""
    import re as _re_owm
    # إذا الاسم المخزّن يحتوي على علم (emoji 🇦🇿 ...) → إذن هو اسم دولة
    if _re_owm.search(r'[\U0001F1E0-\U0001F1FF]', province):
        # نبحث في جدول العواصم أولاً بالمحافظة نفسها، ثم بالدولة
        return (COUNTRY_CAPITALS.get(province)
                or COUNTRY_CAPITALS.get(country, "Baghdad"))
    # نحاول التحويل من جدول المحافظات أولاً، ثم نُعيد الاسم كما هو
    return PROVINCE_TO_OWM.get(province, province)
