# -*- coding: utf-8 -*-
# data_rss.py — مصادر RSS الافتراضية والإقليمية
# مُستخرَج من bot_legacy.py

DEFAULT_RSS = {
    "العربية 🇮🇶": [
        # قنوات دولية كبرى
        "https://feeds.bbci.co.uk/arabic/rss.xml",
        "https://www.aljazeera.net/xml/rss/all.xml",
        "https://arabic.rt.com/rss/",
        "https://rss.dw.com/rdf/rss-ara-all",
        "https://www.france24.com/ar/rss",
        "https://arabic.euronews.com/rss",
        "https://www.aa.com.tr/ar/rss/default",
        "https://www.skynewsarabia.com/rss.xml",
        "https://www.alhurra.com/api/zrqomtmopp",
        "https://feeds.bbci.co.uk/arabic/middleeast/rss.xml",
        "https://www.independentarabia.com/rss.xml",
        "https://alarab.co.uk/rss.xml",
        "https://www.elaph.com/rss/",
        "https://www.arabnews.com/rss.xml",
        "https://www.asharqalawsat.com/rss.xml",
        # عراقية
        "https://baghdadtoday.news/rss.xml",
        "https://www.alsumaria.tv/rss",
        "https://shafaq.com/ar/rss.xml",
        "https://www.mawazin.net/rss.xml",
        "https://www.ankawa.org/feed.php",
        "https://ikhnaton2.com/rss.xml",
        "https://www.nasnews.com/rss.xml",
        "https://www.ina.iq/feed",
        "https://www.ultrairaq.ultrasawt.com/rss.xml",
        "https://www.rudaw.net/arabic/rss",
        "https://www.basnews.com/ar/rss",
        "https://www.nrttv.com/ar/rss",
        "https://www.almaalomah.com/feed/",
        "https://almada-paper.com/feed/",
        "https://www.buratha.news/feed/",
        "https://www.alforatnews.iq/feed/",
        "https://alkafeel.net/rss.xml",
        "https://www.alsabah.iq/feed",
        # وكالات عالمية إضافية
        "https://www.middleeasteye.net/ar/rss",
        "https://feeds.skynewsarabia.com/web/rss/2",
        "https://arabi21.com/rss.xml",
        "https://www.alquds.com/feed/",
        "https://www.alaraby.co.uk/rss.xml",
        "https://www.huffpostarabi.com/feed/",
        "https://www.masrawy.com/rssFeed/news",
        "https://www.youm7.com/rss/rss.xml",
        "https://www.alwatan.com.sa/rss.xml",
        # مصادر عراقية إضافية
        "https://www.almothaqaf.com/feed/",
        "https://www.al-monitor.com/rss.xml",
        "https://www.iraq-businessnews.com/feed/",
        "https://www.nin.iq/feed/",
        "https://thenational.ae/rss.xml",
        "https://www.dinarstandard.com/feed",
        "https://www.almasalah.com/feed/",
        "https://www.haberni.com/feed/",
        "https://www.sotaliraq.com/feed/",
        "https://www.awsat.com/feed/",
        # مصادر عربية إضافية
        "https://www.aawsat.com/rss.xml",
        "https://feed.informer.com/digests/HDCJPVKJKZ/feeder",
        "https://www.alkhaleej.ae/rss.xml",
        "https://rss.hespress.com/",
        "https://www.noonpost.com/feed",
        "https://arabic.alibaba.com/rss/rss.xml",
        "https://www.zawya.com/rss/mena-news.rss",
    ],
    "English 🇬🇧": [
        "https://feeds.bbci.co.uk/news/world/rss.xml",
        "https://feeds.bbci.co.uk/news/rss.xml",
        "https://www.aljazeera.com/xml/rss/all.xml",
        "https://rss.dw.com/rdf/rss-en-all",
        "https://www.france24.com/en/rss",
        "https://www.theguardian.com/world/rss",
        "https://www.rt.com/rss/news/",
        "https://feeds.skynews.com/feeds/rss/world.xml",
        "https://www.aa.com.tr/en/rss/default",
        "https://rss.euronews.com/en/news.rss",
        "https://abcnews.go.com/abcnews/internationalheadlines",
        "https://feeds.reuters.com/reuters/topNews",
        "https://feeds.npr.org/1001/rss.xml",
        "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        "https://feeds.washingtonpost.com/rss/world",
        "https://feeds.bbci.co.uk/news/politics/rss.xml",
        "https://www.independent.co.uk/news/world/rss",
        "https://apnews.com/feed",
        # مصادر إنجليزية إضافية
        "https://rss.cnn.com/rss/edition_world.rss",
        "https://feeds.nbcnews.com/nbcnews/public/news",
        "https://feeds.foxnews.com/foxnews/world",
        "https://www.cbsnews.com/latest/rss/world",
        "https://feeds.skynews.com/feeds/rss/home.xml",
        "https://www.politico.com/rss/politics08.xml",
        "https://www.ft.com/rss/home/uk",
        "https://www.economist.com/international/rss.xml",
        "https://feeds.bloomberg.com/news/sitemap.xml",
        "https://www.businessinsider.com/rss",
        "https://rss.dw.com/rdf/rss-en-world",
        "https://www.aa.com.tr/en/rss/default",
        "https://feeds.reuters.com/reuters/businessNews",
        "https://feeds.reuters.com/Reuters/worldNews",
    ],
    "Русский 🇷🇺": [
        "https://feeds.bbci.co.uk/russian/rss.xml",
        "https://russian.rt.com/rss",
        "https://tass.ru/rss/v2.xml",
        "https://rss.dw.com/rdf/rss-ru-all",
        "https://www.rbc.ru/rss/news",
        "https://ria.ru/export/rss2/archive/index.xml",
        "https://www.interfax.ru/rss.asp",
        "https://www.aa.com.tr/ru/rss/default",
        "https://lenta.ru/rss/news",
        "https://www.kommersant.ru/RSS/news.xml",
        "https://www.mk.ru/rss/news/index.xml",
        "https://iz.ru/xml/rss/all.xml",
        "https://www.vesti.ru/vesti.rss",
    ],
    "فارسی 🇮🇷": [
        "https://feeds.bbci.co.uk/persian/rss.xml",
        "https://rss.dw.com/rdf/rss-per-all",
        "https://www.radiofarda.com/api/zrqomtmopp",
        "https://ir.voanews.com/api/zrqomtmopp",
        "https://www.iranintl.com/rss",
        "https://www.aa.com.tr/fa/rss/default",
        "https://www.france24.com/fa/rss",
        "https://www.isna.ir/rss",
        "https://www.irna.ir/rss",
        "https://farsnews.ir/rss.aspx",
        "https://www.mehrnews.com/rss",
        "https://www.tabnak.ir/rss/fa/index.xml",
    ],
    "हिन्दी 🇮🇳": [
        "https://feeds.bbci.co.uk/hindi/rss.xml",
        "https://rss.dw.com/rdf/rss-hin-all",
        "https://www.aa.com.tr/hi/rss/default",
        "https://feeds.feedburner.com/ndtvnews-top-stories",
        "https://www.indiatoday.in/rss/home",
        "https://navbharattimes.indiatimes.com/rssfeedstopstories.cms",
        "https://www.aajtak.in/rss/india.xml",
        "https://www.jagran.com/rss/news-national.xml",
        "https://www.bhaskar.com/rss-feed/1061/",
        "https://www.amarujala.com/rss/breaking-news.xml",
        "https://www.zeenews.india.com/hindi/rss/top-stories.xml",
    ],
    "Português 🇧🇷": [
        "https://feeds.bbci.co.uk/portuguese/rss.xml",
        "https://rss.dw.com/rdf/rss-por-all",
        "https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml",
        "https://g1.globo.com/rss/g1/index.xml",
        "https://www.france24.com/pt/rss",
        "https://www.aa.com.tr/pt/rss/default",
        "https://rss.euronews.com/pt/news.rss",
        "https://www.uol.com.br/rss.xml",
        "https://oglobo.globo.com/rss.xml",
        "https://www.correiobraziliense.com.br/rss/index.xml",
        "https://feeds.folha.uol.com.br/poder/rss091.xml",
        "https://www.publico.pt/api/rss",
    ],
    "Türkçe 🇹🇷": [
        "https://feeds.bbci.co.uk/turkish/rss.xml",
        "https://www.aa.com.tr/tr/rss/default",
        "https://rss.dw.com/rdf/rss-tur-all",
        "https://www.trthaber.com/sondakika.rss",
        "https://www.ntv.com.tr/son-dakika.rss",
        "https://www.sabah.com.tr/rss/anasayfa.xml",
        "https://www.hurriyet.com.tr/rss/anasayfa",
        "https://rss.euronews.com/tr/news.rss",
        "https://www.haberturk.com/rss",
        "https://www.milliyet.com.tr/rss/rssNew/gundem.rss",
        "https://www.cumhuriyet.com.tr/rss/son_dakika.xml",
        "https://www.sozcu.com.tr/feed/",
        "https://www.cnnturk.com/feed/rss/news",
    ],
    "اردو 🇵🇰": [
        "https://feeds.bbci.co.uk/urdu/rss.xml",
        "https://rss.dw.com/rdf/rss-urd-all",
        "https://www.geo.tv/rss",
        "https://www.urduvoa.com/api/zrqomtmopp",
        "https://urdu.arynews.tv/feed/",
        "https://www.dawnnews.tv/feed/",
        "https://dunyanews.tv/rss/urdu",
        "https://jang.com.pk/rss/1",
        "https://www.express.pk/feed/",
        "https://www.samaa.tv/feed/",
        "https://92newshd.tv/feed/",
        "https://www.boltpak.com/feed/",
    ],
    "Deutsch 🇩🇪": [
        "https://rss.dw.com/rdf/rss-de-all",
        "https://www.tagesschau.de/xml/rss2",
        "https://www.spiegel.de/schlagzeilen/index.rss",
        "https://www.aa.com.tr/de/rss/default",
        "https://rss.euronews.com/de/news.rss",
        "https://www.zeit.de/news/rss-aktuell",
        "https://www.sueddeutsche.de/news/rss",
        "https://www.faz.net/rss/aktuell/",
        "https://www.welt.de/feeds/latest.rss",
        "https://www.stern.de/feed/standard/alle-nachrichten/",
        "https://www.focus.de/rss/news_rss.xml",
    ],
    "Українська 🇺🇦": [
        "https://feeds.bbci.co.uk/ukrainian/rss.xml",
        "https://rss.dw.com/rdf/rss-ukr-all",
        "https://www.ukrinform.ua/rss/block-lastnews",
        "https://www.radiosvoboda.org/api/zrqomtmopp",
        "https://www.pravda.com.ua/rss/view_news/",
        "https://www.unian.ua/rss/all_news.rss",
        "https://suspilne.media/rss",
        "https://www.rbc.ua/rss/all.xml",
        "https://tsn.ua/rss/full.rss",
        "https://www.segodnya.ua/rss/all.rss",
    ],
    "Italiano 🇮🇹": [
        "https://rss.dw.com/rdf/rss-it-all",
        "https://www.ansa.it/sito/notizie/topnews/topnews_rss.xml",
        "https://www.repubblica.it/rss/homepage/rss2.0.xml",
        "https://rss.euronews.com/it/news.rss",
        "https://www.aa.com.tr/it/rss/default",
        "https://www.corriere.it/rss/homepage.xml",
        "https://www.lastampa.it/rss.xml",
        "https://www.ilsole24ore.com/rss/mondo.xml",
        "https://www.rainews.it/dl/img/mediaplayer/rss/video.xml",
        "https://www.sky.it/sky-tg24/rss.xml",
        "https://www.tgcom24.mediaset.it/rss/home.xml",
    ],
    "Español 🇲🇽": [
        "https://feeds.bbci.co.uk/mundo/rss.xml",
        "https://rss.dw.com/rdf/rss-es-all",
        "https://www.france24.com/es/rss",
        "https://rss.euronews.com/es/news.rss",
        "https://www.aa.com.tr/es/rss/default",
        "https://www.infobae.com/feeds/rss/",
        "https://cnnespanol.cnn.com/feed/",
        "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
        "https://www.elmundo.es/rss/portada.xml",
        "https://www.elconfidencial.com/rss/",
        "https://www.lavanguardia.com/rss/home.xml",
        "https://www.clarin.com/rss/",
        "https://www.milenio.com/rss",
        "https://www.excelsior.com.mx/rss.xml",
    ],

    # ── فرنسية ──────────────────────────────────────────────────────────────
    "Français 🇫🇷": [
        "https://www.lemonde.fr/rss/une.xml",
        "https://www.lefigaro.fr/rss/figaro_actualites.xml",
        "https://www.france24.com/fr/rss",
        "https://rss.france24.com/rss/fr/actualites",
        "https://rss.dw.com/rdf/rss-fra-all",
        "https://www.euronews.com/fr/rss",
        "https://feeds.bbci.co.uk/french/rss.xml",
        "https://www.rfi.fr/fr/rss",
        "https://www.20minutes.fr/feeds/rss-une.xml",
        "https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml",
        "https://www.leparisien.fr/rss.xml",
        "https://www.lefigaro.fr/rss/figaro_international.xml",
        "https://www.bfmtv.com/rss/news-24-7/",
        "https://www.lapresse.ca/actualites/rss",
    ],
}

# ======== مصادر أخبار مخصصة لكل دولة (مفتاح: رمز العلم) ========
COUNTRY_RSS = {
    # ── العراق ──
    "🇮🇶": [
        "https://baghdadtoday.news/rss.xml",
        "https://www.alsumaria.tv/rss",
        "https://shafaq.com/ar/rss.xml",
        "https://www.mawazin.net/rss.xml",
        "https://www.ina.iq/feed",
        "https://www.nasnews.com/rss.xml",
        "https://www.almaalomah.com/feed/",
        "https://almada-paper.com/feed/",
        "https://www.alsabah.iq/feed",
        "https://www.alforatnews.iq/feed/",
        "https://www.ultrairaq.ultrasawt.com/rss.xml",
        "https://www.buratha.news/feed/",
        "https://www.nin.iq/feed/",
        "https://www.iraq-businessnews.com/feed/",
        "https://ikhnaton2.com/rss.xml",
        "https://www.ankawa.org/feed.php",
        "https://www.almasalah.com/feed/",
        "https://www.sotaliraq.com/feed/",
        "https://www.haberni.com/feed/",
        "https://www.rudaw.net/arabic/rss",
        "https://www.basnews.com/ar/rss",
        "https://www.nrttv.com/ar/rss",
        "https://alkafeel.net/rss.xml",
    ],
    # ── تركيا ──
    "🇹🇷": [
        "https://www.aa.com.tr/tr/rss/default",
        "https://www.hurriyet.com.tr/rss/gundem",
        "https://www.sabah.com.tr/rss/anasayfa.xml",
        "https://www.milliyet.com.tr/rss/rssNew/gundemRss.xml",
        "https://www.sozcu.com.tr/feed/",
        "https://www.cumhuriyet.com.tr/rss",
        "https://www.haberturk.com/rss",
        "https://www.ntv.com.tr/son-dakika.rss",
        "https://www.trthaber.com/anasayfa.rss",
        "https://www.dha.com.tr/rss/guncel.xml",
        "https://www.cnnturk.com/feed/rss/gundem/news",
        "https://www.star.com.tr/rss/rss.asp",
    ],
    # ── إيران ──
    "🇮🇷": [
        "https://www.isna.ir/rss",
        "https://www.irna.ir/rss",
        "https://farsnews.ir/rss.aspx",
        "https://www.mehrnews.com/rss",
        "https://www.tabnak.ir/rss/fa/index.xml",
        "https://www.tasnimnews.com/fa/rss/feed/0/8/0/وكالة-تسنيم-للأنباء",
        "https://www.khabaronline.ir/rss",
        "https://www.yjc.ir/fa/rss/allnews",
    ],
    # ── المملكة العربية السعودية ──
    "🇸🇦": [
        "https://www.spa.gov.sa/rss/rss2.php",
        "https://www.okaz.com.sa/rss",
        "https://www.alriyadh.com/rss.xml",
        "https://www.alyaum.com/rss",
        "https://www.arabnews.com/rss.xml",
        "https://www.asharqalawsat.com/rss.xml",
        "https://www.alwatan.com.sa/rss.xml",
    ],
    # ── مصر ──
    "🇪🇬": [
        "https://www.youm7.com/rss/rss.xml",
        "https://www.masrawy.com/rssFeed/news",
        "https://www.almasryalyoum.com/rss",
        "https://www.akhbarelyom.com/rss.xml",
        "https://www.vetogate.com/rss",
        "https://www.elwatannews.com/rss",
        "https://www.dotmsr.com/rss",
    ],
    # ── الأردن ──
    "🇯🇴": [
        "https://www.petra.gov.jo/RssPage.aspx",
        "https://www.alghad.com/feed/",
        "https://www.addustour.com/rss",
        "https://jordantimes.com/feed",
        "https://www.albosala.com/feed/",
    ],
    # ── الكويت ──
    "🇰🇼": [
        "https://www.kuna.net.kw/RssPage.aspx?id=2",
        "https://www.aljarida.com/rss",
        "https://www.alqabas.com/rss",
        "https://www.alanba.com.kw/rss.xml",
        "https://www.alraimedia.com/rss.xml",
    ],
    # ── الإمارات ──
    "🇦🇪": [
        "https://wam.ae/en/rss",
        "https://www.thenational.ae/rss.xml",
        "https://www.khaleejtimes.com/rss",
        "https://www.gulfnews.com/rss",
        "https://www.emiratesnews.ae/feed/",
    ],
    # ── سوريا ──
    "🇸🇾": [
        "https://www.sana.sy/en/?feed=rss2",
        "https://www.enabbaladi.net/feed",
        "https://sneasy.net/rss.xml",
        "https://www.syriahr.com/feed/",
        "https://www.syria.tv/rss.xml",
    ],
    # ── لبنان ──
    "🇱🇧": [
        "https://www.naharnet.com/streams/arabic/rss.xml",
        "https://www.annahar.com/rss",
        "https://www.mtv.com.lb/rss",
        "https://www.lbci.com/rss.xml",
        "https://www.lorientlejour.com/rss.xml",
    ],
    # ── باكستان ──
    "🇵🇰": [
        "https://www.dawn.com/feeds/home",
        "https://www.geo.tv/rss",
        "https://arynews.tv/feed/",
        "https://www.thenews.com.pk/rss/1/8",
        "https://www.express.com.pk/feed/",
        "https://www.jang.com.pk/rss",
    ],
    # ── الهند ──
    "🇮🇳": [
        "https://feeds.feedburner.com/ndtvnews-top-stories",
        "https://www.thehindu.com/news/feeder/default.rss",
        "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
        "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
        "https://indianexpress.com/feed/",
        "https://www.indiatoday.in/rss/home",
    ],
    # ── روسيا ──
    "🇷🇺": [
        "https://tass.ru/rss/v2.xml",
        "https://ria.ru/export/rss2/archive/index.xml",
        "https://rg.ru/xml/index.xml",
        "https://lenta.ru/rss/news",
        "https://www.rbc.ru/rss/news",
        "https://iz.ru/xml/rss/all.xml",
        "https://www.kommersant.ru/RSS/news.xml",
    ],
    # ── أوكرانيا ──
    "🇺🇦": [
        "https://www.ukrinform.ua/rss/block-lastnews",
        "https://www.unian.ua/rss",
        "https://www.pravda.com.ua/rss/",
        "https://www.ukrinform.net/rss/block-worldnews",
        "https://interfax.com.ua/news/general/rss.xml",
    ],
    # ── ألمانيا ──
    "🇩🇪": [
        "https://rss.dw.com/rdf/rss-de-all",
        "https://www.spiegel.de/schlagzeilen/index.rss",
        "https://www.tagesschau.de/xml/rss2",
        "https://www.welt.de/feeds/latest.rss",
        "https://www.faz.net/rss/aktuell/",
        "https://www.sueddeutsche.de/rss",
        "https://www.stern.de/feed",
    ],
    # ── المكسيك / إسبانيا ──
    "🇲🇽": [
        "https://www.jornada.com.mx/rss",
        "https://www.milenio.com/rss",
        "https://www.eluniversal.com.mx/rss.xml",
        "https://www.proceso.com.mx/?feed=rss2",
        "https://www.excelsior.com.mx/rss.xml",
    ],
    "🇪🇸": [
        "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
        "https://www.elmundo.es/rss/portada.xml",
        "https://www.lavanguardia.com/rss/home.xml",
        "https://www.20minutos.es/rss/",
        "https://www.abc.es/rss/feeds/abc_EspanaEspana.xml",
    ],
    # ── فرنسا ──
    "🇫🇷": [
        "https://www.lemonde.fr/rss/une.xml",
        "https://www.lefigaro.fr/rss/figaro_international.xml",
        "https://www.liberation.fr/arc/outboundfeeds/rss",
        "https://www.bfmtv.com/rss/news-24-7/",
        "https://www.lapresse.ca/actualites/rss",
    ],
    # ── إيطاليا ──
    "🇮🇹": [
        "https://www.corriere.it/rss/homepage.xml",
        "https://www.repubblica.it/rss/homepage/rss2.0.xml",
        "https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml",
        "https://www.ilpost.it/feed/",
        "https://www.lastampa.it/rss",
    ],
    # ── البرازيل ──
    "🇧🇷": [
        "https://feeds.bbci.co.uk/portuguese/rss.xml",
        "https://g1.globo.com/rss/g1/mundo/",
        "https://www.uol.com.br/rss.xml",
        "https://www.folha.uol.com.br/fsp/poder/rss091.xml",
    ],
}

def _get_country_flag(country_str):
    """يستخرج رمز العلم من اسم الدولة (آخر كلمة تحتوي على emoji)"""
    if not country_str:
        return ""
    parts = country_str.strip().split()
    for part in reversed(parts):
        if any(ord(c) > 127000 for c in part):
            return part
    return ""

def save_keywords():
    save_json(KEYWORDS_FILE, user_keywords)

# ======== تتبع العملات والأسهم ========
tracked_assets = load_json(TRACK_FILE, {})

def save_tracked_assets():
    save_json(TRACK_FILE, tracked_assets)
