# -*- coding: utf-8 -*-
# data_assets.py — رموز العملات والأصول المالية
# مُستخرَج من bot_legacy.py

CRYPTO_IDS = {
    # العملات الرئيسية
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "BNB": "binancecoin",
    "USDT": "tether",
    "USDC": "usd-coin",
    "XRP": "ripple",
    "ADA": "cardano",
    "SOL": "solana",
    "DOGE": "dogecoin",
    "DOT": "polkadot",
    "MATIC": "matic-network",
    "LTC": "litecoin",
    "AVAX": "avalanche-2",
    "SHIB": "shiba-inu",
    "TRX": "tron",
    "LINK": "chainlink",
    "TON": "the-open-network",
    "UNI": "uniswap",
    "ATOM": "cosmos",
    "XLM": "stellar",
    "ALGO": "algorand",
    "VET": "vechain",
    "FIL": "filecoin",
    "HBAR": "hedera-hashgraph",
    "ICP": "internet-computer",
    "APT": "aptos",
    "ARB": "arbitrum",
    "OP": "optimism",
    "MKR": "maker",
    "AAVE": "aave",
    "CRV": "curve-dao-token",
    "FTM": "fantom",
    "NEAR": "near",
    "SUI": "sui",
    "SEI": "sei-network",
    "PEPE": "pepe",
    "WIF": "dogwifcoin",
    "BONK": "bonk",
    "FLOKI": "floki",
    "NOT": "notcoin",
    "DOGS": "dogs-coin",
    "HMSTR": "hamster-kombat",
    "TAO": "bittensor",
    "RENDER": "render-token",
    "INJ": "injective-protocol",
    "PYTH": "pyth-network",
    "JUP": "jupiter-exchange-solana",
    "POPCAT": "popcat",
    "BRETT": "based-brett",
    "TRUMP": "maga",
    "PENGU": "pudgy-penguins",
    "LUNA": "terra-luna-2",
    "SAND": "the-sandbox",
    "APE": "apecoin",
    "MANA": "decentraland",
    "CRO": "crypto-com-chain",
}

FIAT_CURRENCIES = {
    "USD", "EUR", "GBP", "IQD", "SAR", "AED", "TRY",
    "JPY", "CNY", "KWD", "EGP", "JOD", "IRR", "PKR",
    "INR", "BRL", "RUB", "MXN", "CAD", "AUD", "CHF",
    "SEK", "NOK", "DKK", "SGD", "HKD", "QAR", "BHD",
    "OMR", "MAD", "TND", "DZD", "LYD", "SYP", "YER",
    "UAH", "PLN", "CZK", "HUF", "RON", "IDR", "MYR",
    "THB", "PHP", "VND", "ZAR", "NGN",
}

# أسهم شهيرة وسلع — تُجلب من Yahoo Finance
YAHOO_SYMBOLS = {
    # أسهم التكنولوجيا الكبرى
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "GOOGL": "Google",
    "AMZN": "Amazon",
    "NVDA": "NVIDIA",
    "META": "Meta",
    "TSLA": "Tesla",
    "AMD": "AMD",
    "INTC": "Intel",
    "NFLX": "Netflix",
    "ORCL": "Oracle",
    "IBM": "IBM",
    "QCOM": "Qualcomm",
    "AVGO": "Broadcom",
    "CRM": "Salesforce",
    # أسهم أخرى
    "JPM": "JPMorgan",
    "BAC": "Bank of America",
    "WMT": "Walmart",
    "KO": "Coca-Cola",
    "PEP": "PepsiCo",
    "DIS": "Disney",
    "BABA": "Alibaba",
    "TSM": "TSMC",
    "NKE": "Nike",
    "PYPL": "PayPal",
    "UBER": "Uber",
    "SPOT": "Spotify",
    "SNAP": "Snap",
    "X": "X (Twitter)",
    "COIN": "Coinbase",
    "HOOD": "Robinhood",
    "ADBE": "Adobe",
    "CSCO": "Cisco",
    # بنوك ومالية
    "GS": "Goldman Sachs",
    "MS": "Morgan Stanley",
    "WFC": "Wells Fargo",
    "C": "Citigroup",
    "CFG": "Citizens Financial",
    "HSBC": "HSBC",
    "BNP.PA": "BNP Paribas",
    "DBK.DE": "Deutsche Bank",
    "BARC.L": "Barclays",
    # صناعة وطاقة
    "XOM": "ExxonMobil",
    "CVX": "Chevron",
    "BP": "BP",
    "TTE": "TotalEnergies",
    "GE": "GE",
    "BA": "Boeing",
    "CAT": "Caterpillar",
    "SIE.DE": "Siemens",
    "HON": "Honeywell",
    "LMT": "Lockheed Martin",
    # مستهلك وخدمات
    "MCD": "McDonald's",
    "SBUX": "Starbucks",
    "MC.PA": "LVMH",
    "ULVR.L": "Unilever",
    "NESN.SW": "Nestlé",
    "ADS.DE": "Adidas",
    # رعاية صحية
    "PFE": "Pfizer",
    "JNJ": "Johnson & Johnson",
    "MRNA": "Moderna",
    "MRK": "Merck",
    "AZN": "AstraZeneca",
    "LLY": "Eli Lilly",
    "SNY": "Sanofi",
    "NVS": "Novartis",
    "ROG.SW": "Roche",
    # سلع
    "GC=F": "Gold",
    "SI=F": "Silver",
    "CL=F": "Oil (WTI)",
    "BZ=F": "Oil (Brent)",
    "NG=F": "Natural Gas",
    "HG=F": "Copper",
    "PL=F": "Platinum",
    "PA=F": "Palladium",
    # مؤشرات
    "^GSPC": "S&P 500",
    "^IXIC": "NASDAQ",
    "^DJI": "Dow Jones",
    "^FTSE": "FTSE 100",
    "^N225": "Nikkei 225",
    "^HSI": "Hang Seng",
}